all: main1 main2 main3 main4 main5 main6

main1: main1.cpp
	g++ main1.cpp -std=c++17 -o main1

main2: main2.cpp
	g++ main2.cpp -std=c++17 -o main2

main3: main3.cpp
	g++ main3.cpp -std=c++17 -o main3

main4: main4.cpp
	g++ main4.cpp -std=c++11 -o main4

main5: main5.cpp
	g++ main5.cpp -std=c++11 -o main5

main6: main6.cpp
	g++ main6.cpp -std=c++11 -o main6

.PHONY: clean

clean:
	rm -rf main1 main2 main3 main4 main5 main6
