all: main1 main2 main3

main1: main1.cpp
	g++ main1.cpp -std=c++17 -o main1

main2: main2.cpp
	g++ main2.cpp -std=c++17 -o main2

main3: main3.cpp
	g++ main3.cpp -std=c++17 -o main3

.PHONY: clean

clean:
	rm main1 main2 main3
